// ⚠️ MOCK DATA — FOR TESTING ONLY. Remove when backend is connected.

import { Patient } from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    pid: "p1",
    name: "James Wilson",
    sex: "M",
    age: 58,
    chief_complaint: "Chest pain radiating to left arm",
    triage_notes: "58M, substernal chest pain 7/10, onset 2h ago. Diaphoretic. PMH: HTN, hyperlipidemia.",
    esi_score: 2,
    color: "grey",
    status: "called_in",
    is_simulated: true,
    version: 1,
    entered_current_status_tick: 0,
  },
  {
    pid: "p2",
    name: "Maria Santos",
    sex: "F",
    age: 34,
    chief_complaint: "Severe abdominal pain, 6 hours",
    triage_notes: "34F, acute RLQ pain 8/10, nausea, low-grade fever 100.4F. Guarding on exam.",
    esi_score: 3,
    color: "yellow",
    status: "er_bed",
    bed_number: 5,
    is_simulated: false,
    version: 3,
    entered_current_status_tick: 5,
    lab_results: [
      { test: "CBC", result: "WBC 14.2k (elevated)", is_surprising: false, arrives_at_tick: 8 },
      { test: "CMP", result: "Normal", is_surprising: false, arrives_at_tick: 8 },
      { test: "CT Abdomen", result: "", is_surprising: false, arrives_at_tick: 25 },
    ],
  },
  {
    pid: "p3",
    name: "Robert Chen",
    sex: "M",
    age: 72,
    chief_complaint: "Fall with hip pain",
    triage_notes: "72M, mechanical fall at home, unable to bear weight on right leg. No LOC.",
    esi_score: 3,
    color: "grey",
    status: "waiting_room",
    is_simulated: true,
    version: 2,
    entered_current_status_tick: 3,
  },
  {
    pid: "p4",
    name: "Sarah Johnson",
    sex: "F",
    age: 28,
    chief_complaint: "Migraine with visual changes",
    triage_notes: "28F, worst headache of life, photophobia, visual scotoma. No fever, no neck stiffness.",
    esi_score: 3,
    color: "grey",
    status: "er_bed",
    bed_number: 2,
    is_simulated: true,
    version: 2,
    entered_current_status_tick: 4,
    lab_results: [
      { test: "CT Head", result: "No acute intracranial pathology", is_surprising: false, arrives_at_tick: 10 },
    ],
  },
  {
    pid: "p5",
    name: "David Park",
    sex: "M",
    age: 45,
    chief_complaint: "Laceration to right forearm",
    triage_notes: "45M, 6cm laceration right forearm from kitchen knife. Bleeding controlled. Neurovascularly intact.",
    esi_score: 4,
    color: "green",
    status: "er_bed",
    bed_number: 8,
    is_simulated: true,
    version: 4,
    entered_current_status_tick: 12,
    lab_results: [
      { test: "Tetanus status", result: "Up to date", is_surprising: false, arrives_at_tick: 6 },
    ],
  },
  {
    pid: "p6",
    name: "Emily Rodriguez",
    sex: "F",
    age: 61,
    chief_complaint: "Shortness of breath, worsening",
    triage_notes: "61F, progressive dyspnea x3 days, SpO2 89% on RA, bilateral crackles. PMH: CHF.",
    esi_score: 2,
    color: "red",
    status: "er_bed",
    bed_number: 1,
    is_simulated: true,
    version: 3,
    entered_current_status_tick: 2,
    lab_results: [
      { test: "BNP", result: "2,450 pg/mL (critically elevated)", is_surprising: true, arrives_at_tick: 7 },
      { test: "Troponin", result: "0.89 ng/mL (elevated)", is_surprising: true, arrives_at_tick: 7 },
      { test: "Chest X-ray", result: "Bilateral pulmonary edema", is_surprising: false, arrives_at_tick: 5 },
    ],
  },
  {
    pid: "p7",
    name: "Michael Brown",
    sex: "M",
    age: 19,
    chief_complaint: "Ankle sprain during basketball",
    triage_notes: "19M, inversion injury left ankle playing basketball. Swelling, able to bear weight with pain.",
    esi_score: 5,
    color: "grey",
    status: "waiting_room",
    is_simulated: true,
    version: 1,
    entered_current_status_tick: 6,
  },
  {
    pid: "p8",
    name: "Linda Thompson",
    sex: "F",
    age: 55,
    chief_complaint: "Syncopal episode",
    triage_notes: "55F, witnessed syncope at grocery store. LOC ~30s, now alert. PMH: none known.",
    esi_score: 3,
    color: "grey",
    status: "er_bed",
    bed_number: 11,
    is_simulated: true,
    version: 2,
    entered_current_status_tick: 8,
    lab_results: [
      { test: "ECG", result: "", is_surprising: false, arrives_at_tick: 20 },
      { test: "CBC", result: "Hgb 8.2 (low)", is_surprising: true, arrives_at_tick: 12 },
    ],
  },
  {
    pid: "p9",
    name: "Thomas Wright",
    sex: "M",
    age: 40,
    chief_complaint: "Allergic reaction — facial swelling",
    triage_notes: "40M, lip and tongue swelling after eating shellfish. No stridor. Given epi by EMS.",
    esi_score: 2,
    color: "grey",
    status: "er_bed",
    bed_number: 14,
    is_simulated: true,
    version: 5,
    entered_current_status_tick: 10,
  },
  {
    pid: "p10",
    name: "Karen Lee",
    sex: "F",
    age: 38,
    chief_complaint: "Wrist pain after fall",
    triage_notes: "38F, FOOSH injury, tenderness over distal radius. Neurovascularly intact.",
    esi_score: 4,
    color: "green",
    status: "done",
    is_simulated: true,
    version: 6,
    entered_current_status_tick: 18,
  },
];

let nextMockId = 11;

export function getNextMockPatient(): Patient {
  const names = ["Alex Turner", "Nina Patel", "Oscar Mendez", "Grace Kim", "Felix Dubois"];
  const complaints = [
    "Fever and cough x3 days",
    "Nausea and vomiting",
    "Lower back pain",
    "Skin rash spreading",
    "Dizziness and lightheadedness",
  ];
  const i = (nextMockId - 11) % names.length;
  const patient: Patient = {
    pid: `p${nextMockId++}`,
    name: names[i],
    sex: Math.random() > 0.5 ? "M" : "F",
    age: Math.floor(Math.random() * 60) + 18,
    chief_complaint: complaints[i],
    triage_notes: `Auto-generated simulated patient. ${complaints[i]}.`,
    esi_score: Math.floor(Math.random() * 4) + 2,
    color: "grey",
    status: "called_in",
    is_simulated: true,
    version: 1,
    entered_current_status_tick: 0,
  };
  return patient;
}
